// This file is generated from sql/sqlite/*.sql by:
//   pnpm run sync:schema
// It is also regenerated automatically by:
//   pnpm typecheck
//   pnpm build
// Do not edit this file directly. Edit sql/sqlite/*.sql instead.

import { cloudflareSqliteSchemaVersion } from "../versions";

export const requiredSchemaVersion = cloudflareSqliteSchemaVersion;

export const schemaMigrations = [
	{
		version: 1,
		name: "init",
		sql: "CREATE TABLE IF NOT EXISTS kumofire_job_definitions (\n\tid TEXT PRIMARY KEY,\n\tname TEXT NOT NULL UNIQUE,\n\thandler TEXT NOT NULL,\n\tpayload_template TEXT,\n\tdefault_options TEXT,\n\tcreated_at TEXT NOT NULL,\n\tupdated_at TEXT NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS kumofire_job_runs (\n\tid TEXT PRIMARY KEY,\n\tjob_id TEXT NOT NULL,\n\tjob_name TEXT NOT NULL,\n\tstatus TEXT NOT NULL,\n\tdedupe_key TEXT,\n\tpayload TEXT NOT NULL,\n\tattempt INTEGER NOT NULL DEFAULT 0,\n\tmax_attempts INTEGER NOT NULL,\n\tnext_run_at TEXT,\n\tcreated_at TEXT NOT NULL,\n\tupdated_at TEXT NOT NULL,\n\tstarted_at TEXT,\n\tfinished_at TEXT,\n\tlast_error TEXT,\n\tFOREIGN KEY (job_id) REFERENCES kumofire_job_definitions(id)\n);\n\nCREATE INDEX IF NOT EXISTS kumofire_job_runs_status_next_run_at_idx\n\tON kumofire_job_runs (status, next_run_at);\n\nCREATE UNIQUE INDEX IF NOT EXISTS kumofire_job_runs_dedupe_key_idx\n\tON kumofire_job_runs (dedupe_key)\n\tWHERE dedupe_key IS NOT NULL;\n\nCREATE TABLE IF NOT EXISTS kumofire_job_locks (\n\tjob_run_id TEXT PRIMARY KEY,\n\tlease_until TEXT NOT NULL,\n\tupdated_at TEXT NOT NULL\n);\n\nCREATE TABLE IF NOT EXISTS kumofire_schema_version (\n\tversion INTEGER PRIMARY KEY,\n\tupdated_at TEXT NOT NULL\n);\n\nINSERT INTO kumofire_schema_version (version, updated_at)\nVALUES (1, '1970-01-01T00:00:00.000Z')\nON CONFLICT(version) DO UPDATE SET\n\tupdated_at = excluded.updated_at;",
	},
	{
		version: 2,
		name: "job_schedules",
		sql: "CREATE TABLE IF NOT EXISTS kumofire_job_schedules (\n\tid TEXT PRIMARY KEY,\n\tjob_id TEXT NOT NULL,\n\tjob_name TEXT NOT NULL,\n\tschedule_type TEXT NOT NULL,\n\tschedule_expr TEXT NOT NULL,\n\ttimezone TEXT,\n\tnext_run_at TEXT,\n\tlast_scheduled_at TEXT,\n\tenabled INTEGER NOT NULL DEFAULT 1,\n\tpayload TEXT NOT NULL,\n\tmax_attempts INTEGER NOT NULL,\n\tcreated_at TEXT NOT NULL,\n\tupdated_at TEXT NOT NULL,\n\tFOREIGN KEY (job_id) REFERENCES kumofire_job_definitions(id)\n);\n\nCREATE INDEX IF NOT EXISTS kumofire_job_schedules_enabled_next_run_at_idx\n\tON kumofire_job_schedules (enabled, next_run_at);\n\nALTER TABLE kumofire_job_runs\nADD COLUMN job_schedule_id TEXT REFERENCES kumofire_job_schedules(id);\n\nCREATE INDEX IF NOT EXISTS kumofire_job_runs_job_schedule_id_idx\n\tON kumofire_job_runs (job_schedule_id);\n\nINSERT INTO kumofire_schema_version (version, updated_at)\nVALUES (2, '1970-01-01T00:00:00.000Z')\nON CONFLICT(version) DO UPDATE SET\n\tupdated_at = excluded.updated_at;",
	},
] as const;
